name: build

on:
  - push
  - pull_request

jobs:
  php-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: make check -k

      - name: PHPStan xml report
        if: always()
        run: |
          mkdir -p build/phpstan
          vendor/bin/phpstan analyse --no-progress --error-format=checkstyle > build/phpstan/checkstyle.xml

      - name: Analysis Publisher
        uses: digirati-labs/analysis-publisher@0.0.1
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            --report-type=checkstyle --path=**/build/phpcs/checkstyle.xml
            --report-type=checkstyle --path=**/build/phpstan/checkstyle.xml
            --publisher=github_check

      - name: Coveralls publish
        if: always()
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require --quiet --no-interaction cedx/coveralls
          vendor/bin/coveralls build/phpunit/cov.xml
